#cloud-config
autoinstall:
  version: 1
  # Configuración inicial
  locale: es_ES.UTF-8
  keyboard:
    layout: es
    variant: ''
  timezone: America/Bogota
  # Configuración de red (opcional)
  network:
    ethernets:
      enp0s3:
        dhcp4: true
    version: 2
  # Configuración de usuarios
  user-data:
    users:
      - name: pepe
        gecos: Pepe User
        passwd: "$6$exDY1mhS4KUYCE/2$z7Xb9nVfrt9gV2+3f9e9/9" # Contraseña encriptada
        lock_passwd: false
        shell: /bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL
  # Configuración de identidad
  identity:
    hostname: pepe-Nitro-AN515-45
    username: pepe
    password: "$6$exDY1mhS4KUYCE/2$z7X9nVfrt9gV2+3f9e9/9" # Contraseña encriptada
  # Configuración de almacenamiento
  storage:
    config:
      - type: disk
        id: nvme0n1
        ptable: gpt
        wipe: superblock
        match:
          serial: Samsung_SSD_970_EVO_Plus_1TB_S59ANM0R121369J
        partitions:
          - id: nvme0n1p1
            type: partition
            size: 1G
            flag: boot
            filesystem: ext4
            mount: /boot/efi
            wipe: superblock
          - id: nvme0n1p2
            type: partition
            size: 2G
            wipe: superblock
          - id: nvme0n1p3
            type: partition
            size: 4G
            wipe: superblock
          - id: nvme0n1p4
            type: partition
            size: -1  # Resto del disco
            wipe: superblock
      - type: zpool
        id: rpool
        pool: rpool
        vdevs:
          - id: rpool-vdev
            type: disk
            path: /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_1TB_S59ANM0R121369J-part4
      - type: zpool
        id: bpool
        pool: bpool
        mountpoint: /boot
        vdevs:
          - id: bpool-vdev
            type: mirror
            devices:
              - /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_1TB_S59ANM0R121369J-part2
              - /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_1TB_S59ANM0R121369J-part3
      - type: zfs
        id: rpool_ROOT
        pool: rpool
        dataset: rpool/ROOT
        properties:
          mountpoint: none
          canmount: off
      - type: zfs
        id: rpool_ROOT_ubuntu
        pool: rpool  
        dataset: rpool/ROOT/ubuntu
        properties:
          mountpoint: /
          canmount: on
      - type: zfs
        id: rpool_home
        pool: rpool
        dataset: rpool/home
        properties:
          mountpoint: /home
          canmount: on
      - type: zfs
        id: bpool_BOOT
        pool: bpool
        dataset: bpool/BOOT
        properties:
          mountpoint: /boot
          canmount: on
      - type: disk
        id: nvme1n1
        ptable: gpt
        wipe: superblock
        match:
          serial: WDC_PC_SN530_SDBPNPZ-256G-1114
        partitions:
          - id: nvme1n1p1
            type: partition
            size: 1G
            flag: boot
            filesystem: vfat
            wipe: superblock
          - id: nvme1n1p2
            type: partition
            size: -1  # Resto del disco
            filesystem: ext4
            wipe: superblock
            mount: /mnt/disco250
  # Configuración de paquetes
  early-commands:
    - apt-get update
    - apt-get install -y zfsutils-linux
  packages:
    - zfsutils-linux 
    - openssh-server
    - zfs-initramfs
    - linux-modules-extra-$(uname -r)
  # Actualizaciones y limpieza
  updates: security
  late-commands:
    - echo 'REMAKE_INITRD=yes' > /target/etc/dkms/zfs.conf
    - curtin in-target --target=/target -- update-initramfs -u -k all
    - curtin in-target --target=/target -- update-grub
    - mkdir -p /target/mnt/disco250